### ISSUE TITLE
训练paraformer报错RuntimeError: apply_effects_tensor requires sox extension which is not available. Please refer to the stacktrace above for how

### ISSUE THREAD

**Issue by sister-tong** [modelscope/FunASR#1035]
OS：Ubuntu
python version:3.8.18
Package Version：funasr==0.8.1 modelscope==1.9.3 torch==2.1.0 torchaudio==2.1.0
Model：train_asr_paraformer_conformer_12e_6d_2048_256_zh_char
Command：bash run.sh --stage 0 --stop_stage 5
Details：在trrain.log中
Traceback (most recent call last):
  File "/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/FunASR/funasr/datasets/small_datasets/dataset.py", line 216, in __getitem__
    value = loader[uid]
  File "/root/autodl-tmp/FunASR/funasr/datasets/small_datasets/dataset.py", line 39, in __getitem__
    retval = self.loader[key]
  File "/root/autodl-tmp/FunASR/funasr/fileio/sound_scp.py", line 131, in __getitem__
    array, _ = torchaudio.sox_effects.apply_effects_tensor(
  File "/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torchaudio/_extension/utils.py", line 209, in wrapped
    raise RuntimeError(
RuntimeError: apply_effects_tensor requires sox extension which is not available. Please refer to the stacktrace above for how to resolve this.
Errorlog:
asr_inference.1.log中报错
Traceback (most recent call last):
  File "/root/miniconda3/envs/funasr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/funasr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/autodl-tmp/FunASR/funasr/bin/asr_inference_launch.py", line 2505, in <module>
    main()
  File "/root/autodl-tmp/FunASR/funasr/bin/asr_inference_launch.py", line 2500, in main
    inference_pipeline = inference_launch(**kwargs)
  File "/root/autodl-tmp/FunASR/funasr/bin/asr_inference_launch.py", line 2199, in inference_launch
    return inference_paraformer(**kwargs)
  File "/root/autodl-tmp/FunASR/funasr/bin/asr_inference_launch.py", line 309, in inference_paraformer
    speech2text = Speech2TextParaformer(**speech2text_kwargs)
  File "/root/autodl-tmp/FunASR/funasr/bin/asr_infer.py", line 290, in __init__
    asr_model, asr_train_args = build_model_from_file(
  File "/root/autodl-tmp/FunASR/funasr/build_utils/build_model_from_file.py", line 72, in build_model_from_file
    model_dict = torch.load(model_file, map_location=device)
  File "/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/FunASR/egs/aishell/paraformer/result_exp/exp/baseline_train_asr_paraformer_conformer_12e_6d_2048_256_zh_char_exp1/valid.acc.ave_10best.pb'

**Comment by hnluo** [comment]
Please check whether torchaudio is installed successfully

**Comment by sister-tong** [comment]
> 请检查火炬音频是否安装成功

Import TorchAudio shows OK

**Comment by NEUzht** [comment]
How is this issue resolved?
