### ISSUE TITLE
Syntax error: Bad for loop variable

### ISSUE THREAD

**Issue by DTDwind** [modelscope/FunASR#1222]
我运行alimeeting diarization 的 [run.sh](https://github.com/alibaba-damo-academy/FunASR/blob/main/egs/alimeeting/diarization/sond/run.sh)遇到错误，先是`utils/parse_options.sh`不存在。

我参考别的档案补上`../../../aishell/transformer/utils/`之后遇到run.sh: 34: utils/parse_options.sh: Syntax error: Bad for loop variable，不确定这个错误如何修復。

请问能协助我修正这个错误吗？

**Comment by DTDwind** [comment]
我跳过执行`. utils/parse_options.sh || exit 1;`在 [run.sh#33](https://github.com/alibaba-damo-academy/FunASR/blob/e0d06a1da291f31c5af357abbffa87bac3d1c384/egs/alimeeting/diarization/sond/run.sh#L33C28-L33C28)遇到错误`No such file or directory: 'sond.pb'`，我改成绝对路径指向`speech_diarization_sond-zh-cn-alimeeting-16k-n16k4-pytorch/sond.pth`遇到以下错误:
```
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use
 e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

```

**Comment by DTDwind** [comment]
我修復了numpy的错误，之后卡在以下错误:
```
2024-01-08 13:45:13,471 (build_model_from_file:56) INFO: model_file is /mnt/HDD/HDD2/DTDwind/FunASR/egs/alimeeting/diarization/sond/speech_diarization_sond-zh-cn-alimeeting-16k-n16k4-pytorch/sond.pth
Traceback (most recent call last):
  File "infer_alimeeting_test.py", line 24, in <module>
    main()
  File "infer_alimeeting_test.py", line 13, in main
    pipeline = inference_launch(
  File "/mnt/HDD/HDD2/DTDwind/FunASR/funasr/bin/diar_inference_launch.py", line 338, in inference_launch
    return inference_sond(mode=mode, **kwargs)
  File "/mnt/HDD/HDD2/DTDwind/FunASR/funasr/bin/diar_inference_launch.py", line 110, in inference_sond
    speech2diar = Speech2DiarizationSOND(**speech2diar_kwargs)
  File "/mnt/HDD/HDD2/DTDwind/FunASR/funasr/bin/diar_infer.py", line 135, in __init__
    diar_model, diar_train_args = build_model_from_file(
  File "/mnt/HDD/HDD2/DTDwind/FunASR/funasr/build_utils/build_model_from_file.py", line 72, in build_model_from_file
    model_dict = torch.load(model_file, map_location=device)
  File "/home/DTDwind/.conda/envs/funasr/lib/python3.8/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/DTDwind/.conda/envs/funasr/lib/python3.8/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
Traceback (most recent call last):
  File "local/convert_label_to_rttm.py", line 132, in <module>
    my_runner.run()
  File "/mnt/HDD/HDD2/DTDwind/FunASR/funasr/utils/job_runner.py", line 96, in run
    task_list, shared_param, args = self.prepare(parser)
  File "local/convert_label_to_rttm.py", line 26, in prepare
    utt2labels = load_scp_as_list(args.label_txt, 'list')
  File "/mnt/HDD/HDD2/DTDwind/FunASR/funasr/utils/misc.py", line 39, in load_scp_as_list
    with io.open(scp_path, 'r', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/labels.txt'
Scoring...
Loading speaker turns from reference RTTMs...
Loading speaker turns from system RTTMs...
ERROR: Unable to open RTTM file: outputs/prediction_sm_83.rttm
```
OS: linux
Python/C++ Version：Python 3.8.18
Package Version： torch 2.1.2 、torchaudio 2.1.1、modelscope 1.10.0、funasr 0.8.8 、 numpy 1.24.4

**Comment by donggelaile** [comment]
我这里把指令 sh run.sh 换成 bash run.sh 就好了，应该是二者语法差异导致的
