### ISSUE TITLE
[src/libmpg123/parse.c:wetwork():1365] error: Giving up resync after 1024 bytes

### ISSUE THREAD

**Issue by qianqianque163645546464** [modelscope/FunASR#1471]
#### 
The code runtime reported the following error

Note: Illegal Audio-MPEG-Header 0x68746d6c at offset 584064.
Note: Trying to resync...
Note: Skipped 1024 bytes in input.
[src/libmpg123/parse.c:wetwork():1365] error: Giving up resync after 1024 bytes - your stream is not nice... (maybe increasing resync limit could help).
Traceback (most recent call last):
  File "/home/wangyu/Disk/tools/vllm-gptq/tests/qwen/zheng_qwen_0311.py", line 25, in <module>
    res = model.generate(input=f"{model.model_path}/example/test06.wav", 
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 206, in generate
    return self.inference(input, input_len=input_len, **cfg)
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 240, in inference
    results, meta_data = model.inference(**batch, **kwargs)
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/models/bicif_paraformer/model.py", line 247, in inference
    audio_sample_list = load_audio_text_image_video(data_in, fs=frontend.fs, audio_fs=kwargs.get("fs", 16000))
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/utils/load_utils.py", line 34, in load_audio_text_image_video
    return [load_audio_text_image_video(audio, fs=fs, audio_fs=audio_fs, data_type=data_type, **kwargs) for audio in data_or_path_or_list]
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/utils/load_utils.py", line 34, in <listcomp>
    return [load_audio_text_image_video(audio, fs=fs, audio_fs=audio_fs, data_type=data_type, **kwargs) for audio in data_or_path_or_list]
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/utils/load_utils.py", line 41, in load_audio_text_image_video
    data_or_path_or_list, audio_fs = torchaudio.load(data_or_path_or_list)
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/torchaudio/_backend/utils.py", line 205, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/torchaudio/_backend/soundfile.py", line 27, in load
    return soundfile_backend.load(uri, frame_offset, num_frames, normalize, channels_first, format)
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/torchaudio/_backend/soundfile_backend.py", line 230, in load
    waveform = file_.read(frames, dtype, always_2d=True)
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/soundfile.py", line 895, in read
    frames = self._array_io('read', out, frames)
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/soundfile.py", line 1344, in _array_io
    return self._cdata_io(action, cdata, ctype, frames)
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/soundfile.py", line 1354, in _cdata_io
    _error_check(self._errorcode)
  File "/home/wangyu/miniconda3/envs/pinpan/lib/python3.10/site-packages/soundfile.py", line 1407, in _error_check
    raise LibsndfileError(err, prefix=prefix)
soundfile.LibsndfileError: Unspecified internal error.
  0%|                                                                                             | 0/2 [00:00<?, ?it/s]

####  code
from funasr import AutoModel
model = AutoModel(model="/home/wangyu/Disk/tools/Moda-shengwen/", ）
res = model.generate(input=f"{model.model_path}/example/test06.wav", 
                     )
#### 
This audio is in WAV format and can be played. It can be transcribed normally using Whispe Large v3. Does anyone know the reason for this?

 - OS (Linux):
 - FunASR Version 1.0.0:
 - ModelScope Version 1.11.0:

**Comment by Adenialzz** [comment]
Hi, have you solved this?
