### ISSUE TITLE
AttributeError: 'str' object has no attribute '__path__'

### ISSUE THREAD

**Issue by monkeycc** [modelscope/FunASR#1572]
ubuntu
git clone https://github.com/alibaba-damo-academy/FunASR

```python
from funasr import AutoModel
# paraformer-zh is a multi-functional asr model
# use vad, punc, spk or not as you need
model = AutoModel(model="paraformer-zh",  vad_model="fsmn-vad",  punc_model="ct-punc", 
                  # spk_model="cam++", 
                  )
res = model.generate(input=f"{model.model_path}/example/asr_example.wav", 
                     batch_size_s=300, 
                     hotword='魔搭')
print(res)
```

```python
Failed to import funasr.auto.auto_frontend: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 12.1 whereas TorchAudio has CUDA version 11.8. Please install the TorchAudio version that matches your PyTorch version.
Failed to import funasr.auto.auto_model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.auto.auto_frontend: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.auto.auto_model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.bin.export: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.bin.inference: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.bin.tokenize_text: No module named 'funasr.utils.cli_utils'
Failed to import funasr.bin.train: cannot import name 'AutoModel' from partially initialized module 'funasr' (most likely due to a circular import) (/home/mm/FunASR/funasr/__init__.py)
Failed to import funasr.bin.export: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.bin.inference: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.bin.tokenize_text: No module named 'funasr.utils.cli_utils'
Failed to import funasr.bin.train: cannot import name 'AutoModel' from partially initialized module 'funasr' (most likely due to a circular import) (/home/mm/FunASR/funasr/__init__.py)
Failed to import funasr.datasets.audio_datasets.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.audio_datasets.preprocessor: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.audio_datasets.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.audio_datasets.preprocessor: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.large_datasets.build_dataloader: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.large_datasets.dataset: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.large_datasets.build_dataloader: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.large_datasets.dataset: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets.preprocessor: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets.preprocessor: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets_qwenaudio.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets_qwenaudio.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets_vicuna.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets_vicuna.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.audio_datasets.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.audio_datasets.preprocessor: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.audio_datasets.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.audio_datasets.preprocessor: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.large_datasets.build_dataloader: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.large_datasets.dataset: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.large_datasets.build_dataloader: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.large_datasets.dataset: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets.preprocessor: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets.preprocessor: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets_qwenaudio.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets_qwenaudio.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets_vicuna.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.datasets.llm_datasets_vicuna.datasets: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.frontends.wav_frontend: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.frontends.wav_frontend: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.bat.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.bat.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.bicif_paraformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.bicif_paraformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.branchformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.branchformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.campplus.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.campplus.utils: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.campplus.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.campplus.utils: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.conformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.conformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.contextual_paraformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.contextual_paraformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.ct_transformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.ct_transformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.ct_transformer_streaming.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.ct_transformer_streaming.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.data2vec.data2vec: No module named 'funasr.frontends.abs_frontend'
Failed to import funasr.models.data2vec.data2vec: No module named 'funasr.frontends.abs_frontend'
Failed to import funasr.models.e_branchformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.e_branchformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.eend.e2e_diar_eend_ola: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.eend.e2e_diar_eend_ola: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.emotion2vec.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.emotion2vec.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.fsmn_vad_streaming.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.fsmn_vad_streaming.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.language_model.rnn.decoders: No module named 'funasr.models.transformer.utils.scorers'
Failed to import funasr.models.language_model.rnn.decoders: No module named 'funasr.models.transformer.utils.scorers'
Failed to import funasr.models.language_model.seq_rnn_lm: No module named 'funasr.train'
Failed to import funasr.models.language_model.transformer_lm: No module named 'funasr.models.encoder'
Failed to import funasr.models.language_model.rnn.decoders: No module named 'funasr.models.transformer.utils.scorers'
Failed to import funasr.models.language_model.rnn.decoders: No module named 'funasr.models.transformer.utils.scorers'
Failed to import funasr.models.language_model.seq_rnn_lm: No module named 'funasr.train'
Failed to import funasr.models.language_model.transformer_lm: No module named 'funasr.models.encoder'
Failed to import funasr.models.lcbnet.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.lcbnet.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.llm_asr.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.llm_asr.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.llm_asr_nar.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.llm_asr_nar.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.mfcca.e2e_asr_mfcca: cannot import name 'ErrorCalculator' from 'funasr.metrics' (/home/mm/FunASR/funasr/metrics/__init__.py)
Failed to import funasr.models.mfcca.mfcca_encoder: No module named 'funasr.models.encoder'
Failed to import funasr.models.mfcca.e2e_asr_mfcca: cannot import name 'ErrorCalculator' from 'funasr.metrics' (/home/mm/FunASR/funasr/metrics/__init__.py)
Failed to import funasr.models.mfcca.mfcca_encoder: No module named 'funasr.models.encoder'
Failed to import funasr.models.monotonic_aligner.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.monotonic_aligner.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.mossformer.e2e_ss: No module named 'funasr.models.base_model'
Failed to import funasr.models.mossformer.mossformer_encoder: No module named 'funasr.models.transformer.mossformer'
Failed to import funasr.models.mossformer.e2e_ss: No module named 'funasr.models.base_model'
Failed to import funasr.models.mossformer.mossformer_encoder: No module named 'funasr.models.transformer.mossformer'
Failed to import funasr.models.paraformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.paraformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.paraformer_streaming.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.paraformer_streaming.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.qwen_audio.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.qwen_audio.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.sa_asr.beam_search_sa_asr: cannot import name 'end_detect' from 'funasr.metrics' (/home/mm/FunASR/funasr/metrics/__init__.py)
Failed to import funasr.models.sa_asr.e2e_sa_asr: No module named 'funasr.layers'
Failed to import funasr.models.sa_asr.beam_search_sa_asr: cannot import name 'end_detect' from 'funasr.metrics' (/home/mm/FunASR/funasr/metrics/__init__.py)
Failed to import funasr.models.sa_asr.e2e_sa_asr: No module named 'funasr.layers'
Failed to import funasr.models.sanm.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.sanm.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.scama.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.scama.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.seaco_paraformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.seaco_paraformer.model: partially initialized module 'torchaudio' has no attribute 'lib' (most likely due to a circular import)
Failed to import funasr.models.sense_voice.model: cannot import name 'whisper_lib' from partially initialized module 'funasr.models.sense_voice.whisper_lib' (most likely due to a circular import) (/home/mm/FunASR/funasr/models/sense_voice/whisper_lib/__init__.py)
Failed to import funasr.models.sense_voice.whisper_lib: cannot import name 'whisper_lib' from partially initialized module 'funasr.models.sense_voice.whisper_lib' (most likely due to a circular import) (/home/mm/FunASR/funasr/models/sense_voice/whisper_lib/__init__.py)
Traceback (most recent call last):
  File "1.py", line 1, in <module>
    from funasr import AutoModel
  File "/home/mm/FunASR/funasr/__init__.py", line 36, in <module>
    import_submodules(__name__)
  File "/home/mm/FunASR/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/mm/FunASR/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/mm/FunASR/funasr/__init__.py", line 33, in import_submodules
    results.update(import_submodules(name))
  File "/home/mm/FunASR/funasr/__init__.py", line 25, in import_submodules
    for loader, name, is_pkg in pkgutil.walk_packages(package.__path__, package.__name__ + '.'):
AttributeError: 'str' object has no attribute '__path__'
```

**Comment by LauraGPT** [comment]
pip install -e .

**Comment by monkeycc** [comment]
版本问题

https://github.com/alibaba-damo-academy/FunASR/tree/dev_lyb
dev_lyb版本成功

最新的版本 报错

**Comment by eleven-monkey** [comment]
> 版本问题
> 
> https://github.com/alibaba-damo-academy/FunASR/tree/dev_lyb dev_lyb版本成功
> 
> 最新的版本 报错

是的，我一直在colab上使用，今天也用不了，和楼主一样的报错。

**Comment by LauraGPT** [comment]
> > 版本问题
> > https://github.com/alibaba-damo-academy/FunASR/tree/dev_lyb dev_lyb版本成功
> > 最新的版本 报错
> 
> 是的，我一直在colab上使用，今天也用不了，和楼主一样的报错。

你安装了吗？ pip install -e .

**Comment by LauraGPT** [comment]
Bug has been fixed. Please update funasr:
```shell
pip pull 
pip install -e .
```
https://github.com/alibaba-damo-academy/FunASR/pull/1580
