### ISSUE TITLE
the VAD model got an error message

### ISSUE THREAD

**Issue by qianqianque163645546464** [modelscope/FunASR#1797]
## 🐛 Bug

When inputting a 40ms long audio sample, the VAD model got an error message

### To Reproduce

Steps to reproduce the behavior :
1.The data is of byte type，as follows：
16Khz
b'\x08\x00\x00\x00\xe8\xff\xd1\xff\xc8\xff\xc7\xff\xb9\xff\x99\xffx\xffi\xffi\xfff\xffX\xffE\xff8\xff<\xffH\xffT\xffX\xffZ\xffX\xffR\xffH\xffC\xffH\xffW\xffh\xffv\xffx\xffl\xffX\xffS\xffh\xff\x8c\xff\xa9\xff\xb9\xff\xc9\xff\xdb\xff\xe8\xff\xef\xff\xf9\xff\t\x00\x18\x00\x14\x00\x08\x00\n\x00\'\x00T\x00x\x00\x87\x00\x87\x00\x86\x00\x88\x00\x89\x00\x88\x00\x85\x00\x88\x00\x91\x00\x98\x00\x94\x00\x87\x00w\x00h\x00]\x00X\x00R\x00H\x007\x00\'\x00\x1e\x00\x18\x00\x0b\x00\xf9\xff\xe5\xff\xd9\xff\xd5\xff\xd8\xff\xdc\xff\xd9\xff\xcb\xff\xb9\xff\xab\xff\xa8\xff\xb2\xff\xc9\xff\xe4\xff\xf8\xff\xfa\xff\xe8\xff\xd2\xff\xc8\xff\xd2\xff\xe9\xff\xf9\xff\xf8\xff\xe9\xff\xd8\xff\xce\xff\xc8\xff\xcb\xff\xd8\xff\xe9\xff\xe8\xff\xd5\xff\xc8\xff\xd9\xff\xf8\xff\x06\x00\xf8\xff\xe2\xff\xd8\xff\xde\xff\xe8\xff\xf7\xff\x08\x00\x15\x00\x17\x00\x10\x00\x07\x00\x04\x00\x08\x00\x11\x00\x18\x00\x13\x00\x08\x00\x02\x00\x08\x00\x14\x00(\x00J\x00x\x00\x9f\x00\xb8\x00\xcb\x00\xe8\x00\x06\x01\x17\x01\x1a\x01\x17\x01\x13\x01\x08\x01\xf2\x00\xd8\x00\xb9\x00\x98\x00u\x00W\x00?\x00(\x00\x13\x00\x07\x00\x06\x00\x07\x00\x08\x00\x07\x00\x07\x00\x07\x00\x0c\x00\x17\x00$\x00(\x00\x1c\x00\x07\x00\xf6\xff\xe8\xff\xdb\xff\xc8\xff\xaf\xff\x98\xff\x8d\xff\x88\xff~\xffh\xffW\xffX\xffe\xffh\xff`\xffY\xffY\xffX\xffQ\xffH\xffG\xffH\xffD\xff9\xff.\xff(\xff+\xff9\xffK\xffX\xffb\xffy\xff\xa9\xff\xe8\xff\x1c\x007\x00I\x00h\x00\x9b\x00\xd8\x00\x0e\x018\x01Y\x01w\x01\x8e\x01\x98\x01\x90\x01x\x01N\x01\x17\x01\xdd\x00\xa8\x00w\x00G\x00\x1b\x00\xf8\xff\xdb\xff\xb8\xff\x8e\xffh\xffS\xffH\xff<\xff)\xff\x15\xff\x08\xff\x06\xff\t\xff\x06\xff\xf9\xfe\xea\xfe\xe9\xfe\xf7\xfe\t\xff\x12\xff\x19\xff"\xff)\xff&\xff)\xffE\xffy\xff\xab\xff\xc9\xff\xd8\xff\xe9\xff\xff\xff\x18\x001\x00H\x00Y\x00h\x00w\x00\x88\x00\x93\x00\x97\x00\x9c\x00\xa8\x00\xb3\x00\xb7\x00\xb6\x00\xb7\x00\xbc\x00\xb7\x00\xa3\x00\x88\x00r\x00g\x00a\x00W\x00I\x007\x00\'\x00\x18\x00\r\x00\x07\x00\x02\x00\xf9\xff\xe8\xff\xd8\xff\xcf\xff\xc8\xff\xc5\xff\xc8\xff\xda\xff\xf8\xff\x19\x007\x00Q\x00h\x00~\x00\x97\x00\xb4\x00\xc7\x00\xcc\x00\xc7\x00\xcb\x00\xd8\x00\xdc\x00\xc7\x00\x9f\x00w\x00a\x00X\x00L\x008\x00\x1d\x00\x08\x00\x00\x00\x08\x00\x17\x00(\x004\x008\x00.\x00\x18\x00\xfd\xff\xe9\xff\xde\xff\xd9\xff\xcd\xff\xb8\xff\x9f\xff\x89\xffx\xffi\xffW\xffI\xffD\xffH\xffM\xffI\xff>\xff8\xff=\xffI\xffS\xffX\xff^\xffh\xfft\xffx\xffr\xffi\xffe\xffh\xffo\xffy\xff\x88\xff\x99\xff\xa4\xff\xa8\xff\xae\xff\xb8\xff\xc3\xff\xc8\xff\xce\xff\xd8\xff\xe9\xff\xf8\xff\x02\x00\x07\x00\x0c\x00\x17\x00-\x00G\x00a\x00x\x00\x8a\x00\x98\x00\x9b\x00\x97\x00\x95\x00\x98\x00\x9a\x00\x98\x00\x96\x00\x98\x00\x96\x00\x88\x00o\x00X\x00E\x008\x00-\x00(\x00"\x00\x18\x00\x08\x00\xf9\xff\xe9\xff\xd9\xff\xca\xff\xc8\xff\xd2\xff\xd9\xff\xce\xff\xb8\xff\xae\xff\xb9\xff\xd1\xff\xe8\xff\xf6\xff\xf9\xff\xf4\xff\xe8\xff\xd8\xff\xc8\xff\xc3\xff\xc8\xff\xcf\xff\xc9\xff\xb7\xff\xa8\xff\xa9\xff\xb8\xff\xcb\xff\xd8\xff\xdc\xff\xd8\xff\xd5\xff\xd8\xff\xe3\xff\xe8\xff\xe3\xff\xd9\xff\xd4\xff\xd9\xff\xe0\xff\xe9\xff\xf2\xff\xf8\xff\xf4\xff\xe8\xff\xe8\xff\xf8\xff\x0e\x00\x18\x00\x12\x00\x07\x00\x04\x00\x08\x00\x0e\x00\x17\x00)\x00G\x00q\x00\x98\x00\xae\x00\xb8\x00\xc7\x00\xe8\x00\x0f\x01\'\x01(\x01\x17\x01\x04\x01\xf8\x00\xf1\x00\xe7\x00\xcf\x00\xa8\x00\x80\x00g\x00Y\x00G\x00.\x00\x18\x00\x0c\x00\x07\x00\x01\x00\xf8\xff\xf3\xff\xf9\xff\x06\x00\x18\x00 \x00\x18\x00\x05\x00\xf9\xff\xf6\xff\xf9\xff\xf6\xff\xe9\xff\xd3\xff\xb8\xff\xa3\xff\x98\xff\x94\xff\x88\xffq\xffX\xffL\xffI\xffF\xffI\xffZ\xffx\xff\x96\xff\xa8\xff\xb6\xff\xc8\xff\xe5\xff\x08\x00/\x00W\x00\x81\x00\xa7\x00\xc6\x00\xd8\x00\xe0\x00\xe8\x00\xf3\x00\xf8\x00\xe9\x00\xc8\x00\x9f\x00x\x00U\x008\x00 \x00\x08\x00\xea\xff\xc9\xff\xb2\xff\xa8\xff\xa3\xff\x99\xff\x8f\xff\x88\xff~\xffi\xffR\xffH\xffJ\xffI\xff@\xff9\xff7\xff8\xff9\xff8\xff9\xff9\xff6\xff8\xffF\xffX\xfff\xffh\xfff\xffh\xffu\xff\x88\xff\x9a\xff\xa8\xff\xb8\xff\xc8\xff\xd4\xff\xd8\xff\xe0\xff\xf8\xff\x1d\x008\x00<\x007\x00<\x00G\x00L\x00G\x00I\x00W\x00f\x00h\x00d\x00h\x00s\x00x\x00q\x00h\x00e\x00g\x00d\x00W\x00G\x008\x00\'\x00\x17\x00\x0c\x00\x08\x00\x08\x00\x08\x00\x01\x00\xf9\xff\xef\xff\xe8\xff\xe7\xff\xe9\xff\xeb\xff\xe9\xff\xdc\xff\xc8\xff\xb8\xff\xb8\xff\xd0\xff\xf8\xff#\x00G\x00b\x00x\x00\x8e\x00\xa7\x00\xc1\x00\xd7\x00\xea\x00\xf7\x00\xfd\x00\xf8\x00\xe4\x00\xc8\x00\xa7\x00\x87\x00m\x00W\x00B\x00\'\x00\x0c\x00\xf9\xff\xed\xff\xe8\xff\xeb\xff\xf8\xff\x0b\x00\x18\x00\x13\x00\x08\x00\x04\x00'
2. The code is as follows:
model_vad = AutoModel(
    model="/home/.cache/modelscope/hub/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/",
    
    model_revision="v2.0.4",
    device='cuda',
    disable_pbar=True,
    disable_log=True,
    #speech_noise_thres=-0.5
)
status_id['status_dict_vad'] = {'cache': {}, 'is_final': False, 'chunk_size': 40}
segments_result = model_vad.generate(input=audio_in, **status_id['status_dict_vad'])[0]["value"]

3. See error

Traceback (most recent call last):
  File "/home/miniconda3/envs/pinpan/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/miniconda3/envs/pinpan/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/asr_server/all.py", line 67, in handle_session
    self.process_packet(session_id, packet)
  File "/home//asr_server/all.py", line 75, in process_packet
    asr_customer(session_id, msg_index, is_speaking, wav_data)
  File "/home/asr_server/all.py", line 36, in asr_customer
    ret = tool_1.ws_serve(status_dict, session_id, wav_data, msg_index_wav, wav_data)
  File "/home/asr_server/tool_1.py", line 322, in ws_serve
    speech_start_i, status_id['speech_end_i'] = async_vad(status_id, data)
  File "/home/asr_server/tool_1.py", line 90, in async_vad
    segments_result = model_vad.generate(input=audio_in, **status_id['status_dict_vad'])[0]["value"]
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 245, in generate
    return self.inference(input, input_len=input_len, **cfg)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 285, in inference
    res = model.inference(**batch, **kwargs)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/models/fsmn_vad_streaming/model.py", line 722, in inference
    segments_i = self.forward(**batch)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/models/fsmn_vad_streaming/model.py", line 562, in forward
    self.ComputeScores(feats, cache=cache)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/models/fsmn_vad_streaming/model.py", line 351, in ComputeScores
    scores = self.encoder(feats, cache=cache["encoder"]).to("cpu")  # return B * T * D
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/models/fsmn_vad_streaming/encoder.py", line 243, in forward
    x1 = self.in_linear1(input)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/funasr/models/fsmn_vad_streaming/encoder.py", line 36, in forward
    output = self.linear(input)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/pinpan/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x0 and 400x140)

### Expected behavior

My two guesses here are:
1. Is the audio sample interval too short causing an error?
2. Are all audio samples in the silent frequency band reporting an error?

### Environment

 - OS ( Linux):
 - FunASR Version (1.0.27):

**Comment by fierceX** [comment]
hi, This error also occurred in my audio. How to handle it or filter it later?
