### ISSUE TITLE
Paraformer finetune ERROR with AIshell data

### ISSUE THREAD

**Issue by Joey-xx** [modelscope/FunASR#1819]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

I run train_from_local.sh by the model "speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch" and aishell data, but get an ERROR when begin to train:
RuntimeError: The size of tensor a (26) must match the size of tensor b (27) at non-singleton dimension 1

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. use aishel data as train and val according to the format ../../../data/list
2. run train_from_local.sh 
3. start to generate train.jsonl and val.jsonl from wav.scp and text.txt,this step is OK
4. begin to train epoch, see error, here is the log:

Model summary:
    Class Name: Paraformer
    Total Number of model parameters: 220.08 M
    Number of trainable parameters: 220.08 M (100.0%)
    Type: torch.float32
[2024-06-14 19:10:37,749][root][INFO] - Build optim
[2024-06-14 19:10:37,752][root][INFO] - Build scheduler
[2024-06-14 19:10:37,752][root][INFO] - Build dataloader
[2024-06-14 19:10:37,753][root][INFO] - Build dataloader
[2024-06-14 19:10:38,282][root][INFO] - total_num of samplers: 120098, ../../../data/list/train.jsonl
[2024-06-14 19:10:38,347][root][INFO] - total_num of samplers: 14326, ../../../data/list/val.jsonl
[2024-06-14 19:10:38,347][root][WARNING] - distributed is not initialized, only single shard
[2024-06-14 19:10:38,367][root][INFO] - Train epoch: 0, rank: 0

Error executing job with overrides: ['++train_data_set_list=../../../data/list/train.jsonl', '++valid_data_set_list=../../../data/list/val.jsonl', '++dataset_conf.batch_size=20000', '++dataset_conf.batch_type=token', '++dataset_conf.num_workers=4', '++train_conf.max_epoch=50', '++train_conf.log_interval=10', '++train_conf.resume=false', '++train_conf.validate_interval=15', '++train_conf.save_checkpoint_interval=15', '++train_conf.keep_nbest_models=50', '++optim_conf.lr=0.0002', '++init_param=/opt/workplace/FunASR/examples/industrial_data_pretraining/paraformer/modelscope_models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pt', '++tokenizer_conf.token_list=/opt/workplace/FunASR/examples/industrial_data_pretraining/paraformer/modelscope_models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/tokens.json', '++frontend_conf.cmvn_file=/opt/workplace/FunASR/examples/industrial_data_pretraining/paraformer/modelscope_models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/am.mvn', '++output_dir=./outputs']
Traceback (most recent call last):
  File "/opt/workplace/FunASR/examples/industrial_data_pretraining/paraformer/../../../funasr/bin/train.py", line 263, in <module>
    main_hydra()
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workplace/FunASR/examples/industrial_data_pretraining/paraformer/../../../funasr/bin/train.py", line 51, in main_hydra
    main(**kwargs)
  File "/opt/workplace/FunASR/examples/industrial_data_pretraining/paraformer/../../../funasr/bin/train.py", line 210, in main
    trainer.train_epoch(
  File "/opt/workplace/FunASR/funasr/train_utils/trainer.py", line 382, in train_epoch
    retval = model(**batch)
             ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workplace/FunASR/funasr/models/paraformer/model.py", line 208, in forward
    loss_att, acc_att, cer_att, wer_att, loss_pre, pre_loss_att = self._calc_att_loss(
                                                                  ^^^^^^^^^^^^^^^^^^^^
  File "/opt/workplace/FunASR/funasr/models/paraformer/model.py", line 309, in _calc_att_loss
    sematic_embeds, decoder_out_1st = self.sampler(
                                      ^^^^^^^^^^^^^
  File "/opt/workplace/FunASR/funasr/models/paraformer/model.py", line 350, in sampler
    decoder_outs = self.decoder(
                   ^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workplace/FunASR/funasr/models/paraformer/decoder.py", line 397, in forward
    x, tgt_mask, memory, memory_mask, _ = self.decoders(x, tgt_mask, memory, memory_mask)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workplace/FunASR/funasr/models/transformer/utils/repeat.py", line 32, in forward
    args = m(*args)
           ^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workplace/FunASR/funasr/models/paraformer/decoder.py", line 106, in forward
    x, _ = self.self_attn(tgt, tgt_mask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workplace/FunASR/funasr/models/sanm/attention.py", line 522, in forward
    inputs = inputs * mask
             ~~~~~~~^~~~~~
RuntimeError: The size of tensor a (26) must match the size of tensor b (27) at non-singleton dimension 1
[2024-06-14 19:10:45,618] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 12942) of binary: /root/miniconda3/envs/funasr/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/funasr/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.2.0', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/funasr/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../../../funasr/bin/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-14_19:10:45
  host      : a5267b6ab75e
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 12942)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

#### Code sample
here is the attention.py, I have tried to use mask = mask[:, :inputs.size(1), :], but get other error, it seems like problem is in inputs

    def forward(self, inputs, mask, cache=None, mask_shfit_chunk=None):
        """
        :param x: (#batch, time1, size).
        :param mask: Mask tensor (#batch, 1, time)
        :return:
        """
        # print("in fsmn, inputs", inputs.size())
        b, t, d = inputs.size()
        # logging.info(
        #     "mask: {}".format(mask.size()))
        if mask is not None:
            mask = torch.reshape(mask, (b, -1, 1))
            # logging.info("in fsmn, mask: {}, {}".format(mask.size(), mask[0:100:50, :, :]))
            if mask_shfit_chunk is not None:
                # logging.info("in fsmn, mask_fsmn: {}, {}".format(mask_shfit_chunk.size(), mask_shfit_chunk[0:100:50, :, :]))
                mask = mask * mask_shfit_chunk
            # logging.info("in fsmn, mask_after_fsmn: {}, {}".format(mask.size(), mask[0:100:50, :, :]))
            # print("in fsmn, mask", mask.size())
            # print("in fsmn, inputs", inputs.size())
            # print(f"inputs shape: {inputs.shape}")
            # print(f"mask shape: {mask.shape}")
            #mask = mask[:, :inputs.size(1), :]
            inputs = inputs * mask

### Expected behavior

I use aishell data and didn't change the train_from_local.sh
I have checked the train.jsonl, it's OK, so I think it should  work

### Environment

 - OS (e.g., Linux): Ubuntu 20.04
 - FunASR Version (e.g., 1.0.0): 1.0.27
 - ModelScope Version (e.g., 1.11.0): 1.15.0
 - PyTorch Version (e.g., 2.0.0): 2.2.0
 - How you installed funasr (`pip`, source): source
 - Python version: 3.12.3
 - GPU (e.g., V100M32) A100
 - CUDA/cuDNN version (e.g., cuda11.7): nvidia-smi cuda 12.3 but print(torch.version.cuda) = 12.1/cuDNN print(torch.backends.cudnn.version()) = 8902
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1) I use ubuntu 20.04 image and install funasr in container
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Sorry, it is a bug. We will fix it sooner.

**Comment by LauraGPT** [comment]
update funasr. Fix is: https://github.com/modelscope/FunASR/pull/1811
