### ISSUE TITLE
初见遇到的datasets的版本问题

### ISSUE THREAD

**Issue by xiaochunxin** [modelscope/FunASR#1887]
刚开始用FUNASR, 一上来配置环境就卡住了。
在安装完modelscope之后，
File "time_prodict.py", line 9, in <module>
    from modelscope.pipelines import pipeline
  File "/usr/local/anaconda3/envs/lbs_py38/lib/python3.8/site-packages/modelscope/pipelines/__init__.py", line 4, in <module>
    from .base import Pipeline
  File "/usr/local/anaconda3/envs/lbs_py38/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 16, in <module>
    from modelscope.msdatasets import MsDataset
  File "/usr/local/anaconda3/envs/lbs_py38/lib/python3.8/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from .ms_dataset import MsDataset
  File "/usr/local/anaconda3/envs/lbs_py38/lib/python3.8/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import load_dataset_with_ctx
  File "/usr/local/anaconda3/envs/lbs_py38/lib/python3.8/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 19, in <module>
    from datasets.data_files import (
ImportError: cannot import name 'get_metadata_patterns' from 'datasets.data_files' (/usr/local/anaconda3/envs/lbs_py38/lib/python3.8/site-packages/datasets/data_files.py)

似乎是datasets的版本不对，我试着安装了多个版本仍然会有不同的错误。看到文档中没有提到这个安装包的版本，我找了很久也没找到解决方法

**Comment by 19832298531** [comment]
现在解决了吗，我也遇到了同样的问题

**Comment by jiangxiaobai222** [comment]
我也遇到了，暂时还没有解决

**Comment by xiangxiang-meifannao** [comment]
try pip install datasets==2.16.0

**Comment by LYRgood** [comment]
我也遇到了该问题

**Comment by yao521521** [comment]
我也遇到了同样的问题

**Comment by LauraGPT** [comment]
遇到问题，就按照模版提issue，提issue的核心是提供有价值的信息。
`俺也一样`信息量=0

**Comment by FreeGodCode** [comment]
Traceback (most recent call last):
  File "/Users/ty/PycharmProjects/dataset_query.py", line 7, in <module>
    from modelscope.msdatasets import MsDataset
  File "/opt/anaconda3/lib/python3.11/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from modelscope.msdatasets.ms_dataset import MsDataset
  File "/opt/anaconda3/lib/python3.11/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import load_dataset_with_ctx
  File "/opt/anaconda3/lib/python3.11/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 19, in <module>
    from datasets.data_files import (
ImportError: cannot import name 'get_metadata_patterns' from 'datasets.data_files' (/opt/anaconda3/lib/python3.11/site-packages/datasets/data_files.py)
