### ISSUE TITLE
AssertionError: C:\.cache\modelscope\hub\damo\speech_fsmn_vad_zh-cn-16k-common-pytorch is not registered

### ISSUE THREAD

**Issue by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [modelscope/FunASR#1923]
运行开源代码中的FunASR\runtime\python\onnxruntime\demo_vad_offline.py文件
from funasr_onnx import Fsmn_vad
from pathlib import Path

model_dir = "damo/speech_fsmn_vad_zh-cn-16k-common-pytorch"
wav_path = "{}/.cache/modelscope/hub/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch/example/vad_example.wav".format(
    Path.home()
)

model = Fsmn_vad(model_dir)

result = model(wav_path)
print(result)
报错.onnx does not exist, begin to export onnx
You are using the latest version of funasr-1.1.2
Traceback (most recent call last):
  File "D:\liu\FunASR-Online-Paraformer-Test-master\FunASR-Online-Paraformer-Test-master\python\onnxruntime\demo_vad_online.py", line 10, in <module>
    model = Fsmn_vad_online(model_dir)
  File "D:\liu\FunASR-Online-Paraformer-Test-master\FunASR-Online-Paraformer-Test-master\python\onnxruntime\funasr_onnx\vad_bin.py", line 230, in __init__
    model = AutoModel(model=model_dir)
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\funasr\auto\auto_model.py", line 124, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "D:\liu\anaconda3\envs\env_name\lib\site-packages\funasr\auto\auto_model.py", line 218, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
AssertionError: C:\Users\MOTA_Jean\.cache\modelscope\hub\damo\speech_fsmn_vad_zh-cn-16k-common-pytorch is not registered
怎么解决啊

**Comment by viviliuwqhduhnwqihwqwudceygysjiwuwnn** [comment]
已解决,重新导包 pip install -U funasr-onnx

                 pip install -U modelscope funasr,就可以了

**Comment by QQbbla** [comment]
funasr version: 1.2.4.
Check update of funasr, and it would cost few times. You may disable it by set `disable_update=True` in AutoModel
You are using the latest version of funasr-1.2.4
Traceback (most recent call last):
  File "/data1/liux/FunASR/infer.py", line 4, in <module>
    model = AutoModel(model="model_zoo/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-offline",
  File "/data1/liux/FunASR/funasr/auto/auto_model.py", line 125, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/data1/liux/FunASR/funasr/auto/auto_model.py", line 261, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
AssertionError: model_zoo/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-offline is not registered
最新还是不行，请问您的funasr和modelscope version是多少
