### ISSUE TITLE
导出SenseVoice的onnx模型报错

### ISSUE THREAD

**Issue by lanyuer** [modelscope/FunASR#1937]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. funasr-export  ++model=SenseVoiceSmall ++quantize=false ++device=cpu
2. 报错：
You are using the latest version of funasr-1.1.2
[2024-07-21 16:27:16,810][root][INFO] - download models from model hub: ms
2024-07-21 16:27:17,353 - modelscope - ERROR - The request model: SenseVoiceSmall does not exist!
Download: SenseVoiceSmall failed!: The request model: SenseVoiceSmall does not exist!
Error executing job with overrides: ['++model=SenseVoiceSmall', '++quantize=false', '++device=cpu']
Traceback (most recent call last):
  File "/usr/local/bin/funasr-export", line 8, in <module>
    sys.exit(main_hydra())
  File "/usr/local/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/usr/local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/usr/local/lib/python3.10/site-packages/funasr/bin/export.py", line 28, in main_hydra
    model = AutoModel(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 124, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 222, in build_model
    model = model_class(**model_conf, vocab_size=vocab_size)
  File "/usr/local/lib/python3.10/site-packages/funasr/models/sense_voice/model.py", line 618, in __init__
    encoder = encoder_class(input_size=input_size, **encoder_conf)
TypeError: None argument after ** must be a mapping, not NoneType
3. See error

**Comment by LauraGPT** [comment]
Wait for a moment, we are working on it now.

**Comment by LauraGPT** [comment]
Now ONNX and Libtorch is added: https://github.com/modelscope/FunASR/tree/main/examples/industrial_data_pretraining/sense_voice
