### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by 714274808** [modelscope/FunASR#1965]
提交后出现：
![4](https://github.com/user-attachments/assets/21811e2c-54b3-42d9-b58e-d5bdb6329789)

install model requirements successfully
WARNING:root:Initializing VideoClipper.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
MoviePy - Writing audio in C:\Users\Administrator\AppData\Local\Temp\gradio\ec1b96341cbda20c56e7126588746194d6fa382a\E4B8BAE4BB80E4B988E8A681E5A49AE8AFBBE4B9A6EFBC9FE8BF99E698AFE68891E590ACE8BF87E69C80E5A5BDE79A84E7AD94E6A188-E78987E6AEB5.wav
MoviePy - Done.
  0%|                                                                                                  | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\anaconda3\envs\funclip\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\anaconda3\envs\funclip\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\anaconda3\envs\funclip\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "E:\FunClip\funclip\launch.py", line 68, in mix_recog
    res_text, res_srt, video_state = video_recog(
  File "E:\FunClip\funclip\launch.py", line 53, in video_recog
    return audio_clipper.video_recog(video_input, sd_switch, hotwords, output_dir=output_dir)
  File "E:\FunClip\funclip\videoclipper.py", line 164, in video_recog
    return self.recog((16000, wav), sd_switch, state, hotwords, output_dir)
  File "E:\FunClip\funclip\videoclipper.py", line 57, in recog
    rec_result = self.funasr_model.generate(data,
  File "D:\anaconda3\envs\funclip\lib\site-packages\funasr\auto\auto_model.py", line 263, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
  File "D:\anaconda3\envs\funclip\lib\site-packages\funasr\auto\auto_model.py", line 336, in inference_with_vad
    res = self.inference(
  File "D:\anaconda3\envs\funclip\lib\site-packages\funasr\auto\auto_model.py", line 302, in inference
    res = model.inference(**batch, **kwargs)
  File "D:\anaconda3\envs\funclip\lib\site-packages\funasr\models\fsmn_vad_streaming\model.py", line 722, in inference
    segments_i = self.forward(**batch)
  File "D:\anaconda3\envs\funclip\lib\site-packages\funasr\models\fsmn_vad_streaming\model.py", line 564, in forward
    self.DetectCommonFrames(cache=cache)
  File "D:\anaconda3\envs\funclip\lib\site-packages\funasr\models\fsmn_vad_streaming\model.py", line 760, in DetectCommonFrames
    frame_state = self.GetFrameState(
  File "D:\anaconda3\envs\funclip\lib\site-packages\funasr\models\fsmn_vad_streaming\model.py", line 522, in GetFrameState
    speech_prob = math.log(sum_score)
ValueError: math domain error

**Comment by Lock1994** [comment]
@714274808  这个问题怎么解决的？
