### ISSUE TITLE
服务器用docker运行发生异常

### ISSUE THREAD

**Issue by randsoy** [modelscope/FunASR#2089]
我有一个音频文件，识别的时候就发生崩溃。

coredump内容如下：
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/workspace/FunASR/runtime/websocket/build/bin/funasr-wss-server --download-mode'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f08ce745a17 in funasr::PostProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&) () from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
[Current thread is 1 (Thread 0x7f08c58b7700 (LWP 182))]
(gdb) bt
#0  0x00007f08ce745a17 in funasr::PostProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&) () from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#1  0x00007f08ce759289 in funasr::WfstDecoder::FinalizeDecode[abi:cxx11](bool, std::vector<float, std::allocator<float> >, std::vector<float, std::allocator<float> >) ()
   from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#2  0x00007f08ce70df3f in funasr::Paraformer::FinalizeDecode[abi:cxx11](funasr::WfstDecoder*&, bool, std::vector<float, std::allocator<float> >, std::vector<float, std::allocator<float> >) ()
   from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#3  0x00007f08ce711fbd in funasr::Paraformer::Forward[abi:cxx11](float*, int, bool, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, void*) () from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#4  0x00007f08ce6c6163 in FunOfflineInferBuffer(void*, char const*, int, FUNASR_MODE, void (*)(int, int), std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, void*) () from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#5  0x00005614199abe67 in WebSocketServer::do_decoder(std::vector<char, std::allocator<char> > const&, std::weak_ptr<void>&, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&, std::mutex&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*&) ()
#6  0x00005614199ba1e5 in asio::detail::executor_op<asio::detail::binder0<std::_Bind<void (WebSocketServer::*(WebSocketServer*, std::vector<char, std::allocator<char> >, std::weak_ptr<void>, std::reference_wrapper<nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > >, std::reference_wrapper<std::mutex>, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, std::reference_wrapper<void*>))(std::vector<char, std::allocator<char> > const&, std::weak_ptr<void>&, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&, std::mutex&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*&)> >, std::allocator<void>, asio::detail::scheduler_operation>::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned long) ()
#7  0x000056141992cab8 in asio::detail::scheduler::run(std::error_code&) ()
#8  0x000056141991d5bd in std::thread::_State_impl<std::thread::_Invoker<std::tuple<main::{lambda()#1}> > >::_M_run() ()
#9  0x00007f08cdfeddf4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f08ce13a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007f08cde29353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
#0  0x00007f08ce745a17 in funasr::PostProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&) () from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#1  0x00007f08ce759289 in funasr::WfstDecoder::FinalizeDecode[abi:cxx11](bool, std::vector<float, std::allocator<float> >, std::vector<float, std::allocator<float> >) ()
   from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#2  0x00007f08ce70df3f in funasr::Paraformer::FinalizeDecode[abi:cxx11](funasr::WfstDecoder*&, bool, std::vector<float, std::allocator<float> >, std::vector<float, std::allocator<float> >) ()
   from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#3  0x00007f08ce711fbd in funasr::Paraformer::Forward[abi:cxx11](float*, int, bool, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, void*) () from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#4  0x00007f08ce6c6163 in FunOfflineInferBuffer(void*, char const*, int, FUNASR_MODE, void (*)(int, int), std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, void*) () from /workspace/FunASR/runtime/websocket/build/src/libfunasr.so
#5  0x00005614199abe67 in WebSocketServer::do_decoder(std::vector<char, std::allocator<char> > const&, std::weak_ptr<void>&, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&, std::mutex&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*&) ()
#6  0x00005614199ba1e5 in asio::detail::executor_op<asio::detail::binder0<std::_Bind<void (WebSocketServer::*(WebSocketServer*, std::vector<char, std::allocator<char> >, std::weak_ptr<void>, std::reference_wrapper<nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > >, std::reference_wrapper<std::mutex>, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, std::reference_wrapper<void*>))(std::vector<char, std::allocator<char> > const&, std::weak_ptr<void>&, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&, std::mutex&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*&)> >, std::allocator<void>, asio::detail::scheduler_operation>::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned long) ()
#7  0x000056141992cab8 in asio::detail::scheduler::run(std::error_code&) ()
#8  0x000056141991d5bd in std::thread::_State_impl<std::thread::_Invoker<std::tuple<main::{lambda()#1}> > >::_M_run() ()
#9  0x00007f08cdfeddf4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f08ce13a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007f08cde29353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by LauraGPT** [comment]
Please describe you issue clearly.

**Comment by lyblsgo** [comment]
辛苦提供可复现的步骤，包括测试音频

**Comment by randsoy** [comment]
音频是有很长一段静音，我找找看，如果找到啦就附加上来。
