### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by dospeech** [modelscope/FunASR#2131]
**When I try to install funasr in a conda environment, I encounter an error. The error message is as follows:

root@ve-dev:/mnt/sensevoice/funASR# pip install -e ./ 
Looking in indexes: https://mirrors.ivolces.com/pypi/simple/
Obtaining file:///mnt/sensevoice/funASR
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
      ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
      ERROR: No matching distribution found for pytest-runner
      /mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/setuptools/dist.py:452: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'index-url' will not be supported in future
              versions. Please use the underscore name 'index_url' instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      /mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/setuptools/installer.py", line 102, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/mnt/anaconda3/envs/sensevoice/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp3ggnalnq', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'pytest-runner']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/sensevoice/funASR/setup.py", line 111, in <module>
          setup(
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/setuptools/__init__.py", line 116, in setup
          _install_setup_requires(attrs)
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/setuptools/__init__.py", line 89, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/setuptools/__init__.py", line 94, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/setuptools/dist.py", line 617, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/setuptools/installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/pkg_resources/__init__.py", line 897, in resolve
          dist = self._resolve_dist(
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/pkg_resources/__init__.py", line 933, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1271, in best_match
          return self.obtain(req, installer)
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1307, in obtain
          return installer(requirement) if installer else None
        File "/mnt/anaconda3/envs/sensevoice/lib/python3.8/site-packages/setuptools/installer.py", line 104, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/mnt/anaconda3/envs/sensevoice/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp3ggnalnq', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'pytest-runner']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

## ❓ Questions and Help

Please tell me how to solve this and how to correctly install it.

### Before asking:
1. search the issues.
2. search the docs.

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):最新版本
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version: Python 3.8.20
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
网上搜一下，pypi源，推荐官方源
