### ISSUE TITLE
Paraformer-en模型在推理时报错，spm index超出范围

### ISSUE THREAD

**Issue by MrSupW** [modelscope/FunASR#2185]
版本：funasr-1.1.14
推理数据集：COMMON_VOICE_V17.0_EN_DEV
报错：
{'load_data': '0.128', 'extract_feat': '0.057', 'forward': '0.624', 'batch_size': '16', 'rtf': '0.006'}, :   2%| | 288/16393 [00:16<11:05Traceback (most recent call last):
  File "/home/xj_data/wanghe.wh/code/Leaderboard/models/paraformer.py", line 33, in <module>
    all_decode_results = model.generate(input=input_wav_scp, batch_size=args.batch_size)
  File "/cpfs/shared/public/wanghe.wh/miniconda/envs/leaderboard/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 301, in generate
    return self.inference(input, input_len=input_len, **cfg)
  File "/cpfs/shared/public/wanghe.wh/miniconda/envs/leaderboard/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 343, in inference
    res = model.inference(**batch, **kwargs)
  File "/cpfs/shared/public/wanghe.wh/miniconda/envs/leaderboard/lib/python3.10/site-packages/funasr/models/paraformer/model.py", line 569, in inference
    token = tokenizer.ids2tokens(token_int)
  File "/cpfs/shared/public/wanghe.wh/miniconda/envs/leaderboard/lib/python3.10/site-packages/funasr/tokenizer/sentencepiece_tokenizer.py", line 54, in ids2tokens
    return self.decode(*args, **kwargs)
  File "/cpfs/shared/public/wanghe.wh/miniconda/envs/leaderboard/lib/python3.10/site-packages/funasr/tokenizer/sentencepiece_tokenizer.py", line 48, in decode
    return self.sp.DecodeIds(line)
  File "/cpfs/shared/public/wanghe.wh/miniconda/envs/leaderboard/lib/python3.10/site-packages/sentencepiece/__init__.py", line 876, in DecodeIds
    return self.Decode(input=input, out_type=out_type, **kwargs)
  File "/cpfs/shared/public/wanghe.wh/miniconda/envs/leaderboard/lib/python3.10/site-packages/sentencepiece/__init__.py", line 801, in Decode
    return self._DecodeIds(input)
  File "/cpfs/shared/public/wanghe.wh/miniconda/envs/leaderboard/lib/python3.10/site-packages/sentencepiece/__init__.py", line 343, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.
{'load_data': '0.128', 'extract_feat': '0.057', 'forward': '0.624', 'batch_size': '16', 'rtf': '0.006'}, :   2%| | 288/16393 [00:17<16:18

**Comment by LauraGPT** [comment]
We suggest you to use `SenseVoiceSmall` install of `paraformer-en`
