### ISSUE TITLE
第一次执行Quick Start中的命令时被意外中断，之后一直报modelscope - ERROR - 400 Client Error: Bad Request，似乎无法下载任何模型

### ISSUE THREAD

**Issue by HexJay** [modelscope/FunASR#2190]
(venv) PS E:\Desktop\FunASR> funasr ++model=paraformer-zh ++vad_model="fsmn-vad" ++punc_model="ct-punc" ++input=wav/asr_example_zh.wav

funasr version: 1.1.14.
Check update of funasr, and it would cost few times. You may disable it by set `disable_update=True` in AutoModel
You are using the latest version of funasr-1.1.14
[2024-11-03 20:21:38,923][root][INFO] - download models from model hub: ms
**2024-11-03 20:21:39,157 - modelscope - ERROR - 400 Client Error: Bad Request, Request id: a4f9236897944a4d8d735e927789f9ad for url: https://www.modelscope.cn/api/v1/models/iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions
Download: iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch failed!: 400 Client Error: Bad Request, Request id: a4f9236897944a4d8d735e927789f9ad for url: https://www.modelscope.cn/api/v1/models/iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions
Error executing job with overrides: ['++model=paraformer-zh', '++vad_model=fsmn-vad', '++punc_model=ct-punc', '++input=wav/asr_example_zh.wav']**

Traceback (most recent call last):
  File "D:\anaconda3\envs\v310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\v310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Desktop\FunASR\venv\Scripts\funasr.exe\__main__.py", line 7, in <module>
  File "E:\Desktop\FunASR\venv\lib\site-packages\hydra\main.py", line 94, in decorated_main
    _run_hydra(
  File "E:\Desktop\FunASR\venv\lib\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "E:\Desktop\FunASR\venv\lib\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "E:\Desktop\FunASR\venv\lib\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "E:\Desktop\FunASR\venv\lib\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
  File "E:\Desktop\FunASR\venv\lib\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "E:\Desktop\FunASR\venv\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "E:\Desktop\FunASR\venv\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "E:\Desktop\FunASR\venv\lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "E:\Desktop\FunASR\venv\lib\site-packages\funasr\bin\inference.py", line 24, in main_hydra
    model = AutoModel(**kwargs)
  File "E:\Desktop\FunASR\venv\lib\site-packages\funasr\auto\auto_model.py", line 125, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "E:\Desktop\FunASR\venv\lib\site-packages\funasr\auto\auto_model.py", line 259, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
**AssertionError: paraformer-zh is not registered**

**Comment by LauraGPT** [comment]
把~/.cacha/modelscope缓存删除
