### ISSUE TITLE
pyinstaller6.11版本打包后运行报错

### ISSUE THREAD

**Issue by SFidea** [modelscope/FunASR#2220]
model loading
funasr version: 1.1.14.
INFO:root:download models from model hub: ms
Traceback (most recent call last):
  File "funasr_wss_server.py", line 83, in <module>
  File "funasr\auto\auto_model.py", line 125, in __init__
  File "funasr\auto\auto_model.py", line 223, in build_model
TypeError: 'NoneType' object is not callable
[PYI-31400:ERROR] Failed to execute script 'funasr_wss_server' due to unhandled exception!
有遇到类似的吗？

**Comment by il-netizen** [comment]
同问， 请问解决了吗 @SFidea 
我看源码，是这一行报错
tokenizer = tokenizer_class(**tokenizer_conf)
是什么依赖包没有打进去吗

**Comment by 313038** [comment]
我也遇到了，怎么解决的

**Comment by wwwvgt** [comment]
看了前面的回答确实是tokenizer = tokenizer_class(**tokenizer_conf)这行代码有问题，打包的时候和QApplication有冲突，如果不引用QApplication，单独打包senseVoice相关的代码是没问题的，但是不知道具体问题出在哪里怎么修改
