### ISSUE TITLE
cannot import name 'AutoModel' from partially initialized module 'funasr' (most likely due to a circular import)

### ISSUE THREAD

**Issue by H4M5TER** [modelscope/FunASR#2221]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. `uv venv -p 3.8`
2. `uv pip install funasr torch torchaudio --extra-index-url https://download.pytorch.org/whl/cu124`
3. `python funasr.py`

```log
Traceback (most recent call last):
  File ".\funasr.py", line 1, in <module>
    from funasr import AutoModel
  File "D:\lab\asr\funasr.py", line 1, in <module>
    from funasr import AutoModel
ImportError: cannot import name 'AutoModel' from partially initialized module 'funasr' (most likely due to a circular import) (D:\lab\asr\funasr.py)
```

#### Code sample

Paraformer Speech Recogition example from README

```py
from funasr import AutoModel
# paraformer-zh is a multi-functional asr model
# use vad, punc, spk or not as you need
model = AutoModel(model="paraformer-zh",  vad_model="fsmn-vad",  punc_model="ct-punc", 
                  # spk_model="cam++", 
                  )
res = model.generate(input=f"{model.model_path}/example/asr_example.wav", 
                     batch_size_s=300, 
                     hotword='魔搭')
print(res)
```

### Environment

 - OS: Windows
 - FunASR: 1.1.14
 - ModelScope: none
 - PyTorch: 2.4.1+cu124
 - How you installed funasr (`pip`, source): pip
 - Python: 3.8.20
 - GPU: NVIDIA RTX 3080
 - CUDA/cuDNN: CUDA 12.6
 - Docker: none
 - Any other relevant information:

```log
> uv pip install funasr torch torchaudio --extra-index-url https://download.pytorch.org/whl/cu124
Resolved 64 packages in 3.42s
Installed 64 packages in 4.53s
 + aliyun-python-sdk-core==2.16.0
 + aliyun-python-sdk-kms==2.16.5
 + antlr4-python3-runtime==4.9.3
 + audioread==3.0.1
 + certifi==2022.12.7
 + cffi==1.17.1
 + charset-normalizer==2.1.1
 + colorama==0.4.6
 + crcmod==1.7
 + cryptography==43.0.3
 + decorator==5.1.1
 + editdistance==0.8.1
 + filelock==3.13.1
 + fsspec==2024.2.0
 + funasr==1.1.14
 + hydra-core==1.3.2
 + idna==3.4
 + importlib-metadata==8.5.0
 + importlib-resources==6.4.5
 + jaconv==0.4.0
 + jamo==0.4.1
 + jieba==0.42.1
 + jinja2==3.1.3
 + jmespath==0.10.0
 + joblib==1.4.2
 + kaldiio==2.18.0
 + lazy-loader==0.4
 + librosa==0.10.2.post1
 + llvmlite==0.41.1
 + markupsafe==2.1.5
 + mpmath==1.3.0
 + msgpack==1.1.0
 + networkx==3.2.1
 + numba==0.58.1
 + numpy==1.24.1
 + omegaconf==2.3.0
 + oss2==2.19.1
 + packaging==24.1
 + platformdirs==4.3.6
 + pooch==1.8.2
 + protobuf==5.28.3
 + pycparser==2.22
 + pycryptodome==3.21.0
 + pynndescent==0.5.13
 + pytorch-wpe==0.0.1
 + pyyaml==6.0.2
 + requests==2.28.1
 + scikit-learn==1.3.2
 + scipy==1.10.1
 + sentencepiece==0.2.0
 + six==1.16.0
 + soundfile==0.12.1
 + soxr==0.3.7
 + sympy==1.13.1
 + tensorboardx==2.6.2.2
 + threadpoolctl==3.5.0
 + torch==2.4.1+cu124
 + torch-complex==0.4.4
 + torchaudio==2.4.1+cu124
 + tqdm==4.66.5
 + typing-extensions==4.9.0
 + umap-learn==0.5.7
 + urllib3==1.26.13
 + zipp==3.20.2
```

### Additional context

尝试把 funasr 降级到 1.1.13 / 1.1.12 / 1.1.0 / 1.0.0
仍然得到同样报错

**Comment by LauraGPT** [comment]
Please do not name it as `funasr.py`. You could save the code as `demo.py` file.
