### ISSUE TITLE
vad_model和punc_model设置本地路径报错

### ISSUE THREAD

**Issue by LIUKAI0815** [modelscope/FunASR#2248]
Traceback (most recent call last):
  File "/workspace/model/llm/audio_model/asr.py", line 6, in <module>
    model = AutoModel(model="./ASR/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404",vad_model="./ASR/iic/speech_fsmn_vad_zh-cn-16k-common-onnx",
  File "/root/miniforge3/envs/audio/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 135, in __init__
    vad_model, vad_kwargs = self.build_model(**vad_kwargs)
  File "/root/miniforge3/envs/audio/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 259, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
AssertionError: ./ASR/iic/speech_fsmn_vad_zh-cn-16k-common-onnx is not registered

代码：import os
from funasr import AutoModel
os.environ['CUDA_VISIBLE_DEVICES'] = "3"
# paraformer-zh is a multi-functional asr model
# use vad, punc, spk or not as you need
model = AutoModel(model="./ASR/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404",vad_model="./ASR/iic/speech_fsmn_vad_zh-cn-16k-common-onnx",
                  punc_model="./ASR/iic/punc_ct-transformer_zh-cn-common-vocab272727-onnx")
res = model.generate(input=f"video.wav", 
            batch_size_s=492, 
            hotword='外呼')
print(res)

**Comment by LIUKAI0815** [comment]
已经解决，是因为路径里用了onnx模型

**Comment by gyhyfj** [comment]
> 已经解决，是因为路径里用了onnx模型

请问 --model-dir 不能支持onnx模型吗，还是低版本不支持呢？
