### ISSUE TITLE
Failed to download `emotion2vec_plus_large` model

### ISSUE THREAD

**Issue by shaoenqin** [modelscope/FunASR#2261]
## 🐛 Bug

Failed to download "iic/emotion2vec_plus_large" model during its initialization.

### To Reproduce

from funasr import AutoModel
model = AutoModel(model="iic/emotion2vec_plus_large")
> funasr version: 1.1.16.
Check update of funasr, and it would cost few times. You may disable it by set `disable_update=True` in AutoModel
You are using the latest version of funasr-1.1.16
Downloading Model to directory: /Users/shaoenqin/.cache/modelscope/hub/iic/emotion2vec_plus_large
2024-12-03 15:04:17,269 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
Download: iic/emotion2vec_plus_large failed!: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/iic/emotion2vec_plus_large/repo/files?Revision=master&Recursive=True (Caused by ResponseError('too many 500 error responses'))
Traceback (most recent call last):
  File "/Users/shaoenqin/opt/anaconda3/envs/atlas_env/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-d7c80563c0a7>", line 3, in <module>
    model = AutoModel(model="iic/emotion2vec_plus_large")
  File "/Users/shaoenqin/opt/anaconda3/envs/atlas_env/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 125, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/Users/shaoenqin/opt/anaconda3/envs/atlas_env/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 259, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
AssertionError: iic/emotion2vec_plus_large is not registered

**Comment by peterbliu** [comment]
same error, could it be the server API overlasting?

> funasr version: 1.1.16.
Downloading Model to directory: /Users/peterliu/.cache/modelscope/hub/iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-12-04 08:23:49,482 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
Download: iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch failed!: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/repo/files?Revision=master&Recursive=True (Caused by ResponseError('too many 500 error responses'))
Traceback (most recent call last):
  File "/Users/peterliu/Coding/Python/openai/media2text 2_sum_srt_chinese.py", line 70, in <module>
    main()
  File "/Users/peterliu/Coding/Python/openai/media2text 2_sum_srt_chinese.py", line 64, in main
    plu.process_file_2txt_2sum_2srt_cn(path, output_path=None, B_TXT_SUM=B_TXT_SUM, B_SRT_SUB=B_SRT_SUB, B_SAVE_RAW_RESULTS=B_SAVE_RAW_RESULTS)
  File "/Users/peterliu/Coding/Python/my_module/misc/p_llm_util.py", line 448, in process_file_2txt_2sum_2srt_cn
    model = AutoModel(model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 125, in __init__
    model, kwargs = self.build_model(**kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/funasr/auto/auto_model.py", line 259, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch is not registered

**Comment by Djraemon** [comment]
The error appears to be a network problem. 
"https://modelscope.cn" cannot be accessed, causing the "iic/emotion2vec_plus_large" model to fail to download. 
Try turning on the VPN and try again? Or to manually download website model file and put them into path "/Users/shaoenqin/cache/modelscope/hub/iic emotion2vec_plus_large".

**Comment by LauraGPT** [comment]
If you are overseas users, please use "hf" to download:

```python
model = AutoModel(
    model=model,
    hub="ms",  # "ms" or "modelscope" for Mainland China users; "hf" or "huggingface" for Other overseas users
)
```

ref to https://github.com/modelscope/FunASR/blob/main/examples/industrial_data_pretraining/emotion2vec/demo.py
