### ISSUE TITLE
RuntimeError: no running event loop

### ISSUE THREAD

**Issue by yz1yang** [modelscope/FunASR#2285]
Python版本下面的funasr_wss_server.py启动会出现没有循环事件的问题
Traceback (most recent call last):
  File "E:\project\FunASR-main\runtime\python\websocket\funasr_wss_server.py", line 337, in <module>
    start_server = websockets.serve(
  File "E:\Miniconda3\envs\huiyi\lib\site-packages\websockets\asyncio\server.py", line 737, in __init__
    self.server = Server(
  File "E:\Miniconda3\envs\huiyi\lib\site-packages\websockets\asyncio\server.py", line 281, in __init__
    self.loop = asyncio.get_running_loop()
RuntimeError: no running event loop

**Comment by yz1yang** [comment]
更换了Python版本，没有报错了，但是一直在异步哪儿，后续的加载一直加载不进去
<img width="1037" alt="企业微信截图_17338143362930" src="https://github.com/user-attachments/assets/ce18e941-c650-41b5-b049-cc62aad9cd11">

**Comment by happywch** [comment]
我也出现这个问题，用的python3.10,但是另外一台电脑部署的也是3.10 没有问题。我这台电脑现在也是1.1.16的funasr请问你最后使用什么版本的python

**Comment by happywch** [comment]
websockets的版本问题，之前14.1,换成12.0就好了

**Comment by yz1yang** [comment]
Python是3.9的，对应更新了funasr，然后就没有模型加载和启动的问题了，就是一直在ws_serve外面

**Comment by yz1yang** [comment]
我试了，更换了websockets的确也可以

**Comment by shaojiajun314** [comment]
解决了吗，。
<img width="894" alt="截屏2025-01-08 15 38 04" src="https://github.com/user-attachments/assets/2d77b6df-aa58-403d-ae0d-f084b795f477" />

**Comment by lovemaoli** [comment]
我也遇到了这个问题，websockets的版本换成12.0就好了，感谢！
