### ISSUE TITLE
stream model_blade.torchscript export 失败

### ISSUE THREAD

**Issue by zhuhao528** [modelscope/FunASR#2288]
[W shape_analysis.cpp:841] failed PropagateTensorShapeOnNode with schema:
aten::linear(Tensor input, Tensor weight, Tensor? bias=None) -> (Tensor)
%4 : Tensor = aten::linear(%input.1, %self.weight, %self.bias) # /usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py:114:15

[W shape_analysis.cpp:841] failed PropagateTensorShapeOnNode with schema:
aten::linear(Tensor input, Tensor weight, Tensor? bias=None) -> (Tensor)
%4 : Tensor = aten::linear(%input.1, %self.weight, %self.bias) # /usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py:114:15

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/FunASR/funasr/download/runtime_sdk_download_tool.py", line 58, in <module>
    main()
  File "/workspace/FunASR/funasr/download/runtime_sdk_download_tool.py", line 51, in main
    export_model.export(
  File "/workspace/FunASR/funasr/auto/auto_model.py", line 662, in export
    export_dir = export_utils.export(model=model, data_in=data_list, **kwargs)
  File "/workspace/FunASR/funasr/utils/export_utils.py", line 37, in export
    _bladedisc_opt_for_encdec(m, path=export_dir, enable_fp16=True)
  File "/workspace/FunASR/funasr/utils/export_utils.py", line 205, in _bladedisc_opt_for_encdec
    model_script = torch.jit.trace(model, input_data)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 750, in trace
    return trace_module(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 967, in trace_module
    module._c._create_method_from_trace(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/workspace/FunASR/funasr/models/paraformer_streaming/export_meta.py", line 64, in export_encoder_forward
    enc, enc_len = self.encoder(**batch)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1107, in _slow_forward
    return self.forward(*input, **kwargs)
RuntimeError: forward() expected at most 3 argument(s) but received 4 argument(s). Declaration: forward(__torch__.funasr.models.sanm.encoder.___torch_mangle_643.SANMEncoderExport self, Tensor speech, Tensor speech_lengths) -> ((Tensor, Tensor))
Notice: ffmpeg is not installed. torchaudio is used to load audio
If you want to use ffmpeg backend to load audio, please install it by:
	sudo apt install ffmpeg # ubuntu
	# brew install ffmpeg # mac
model is not exist, begin to export /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model_blade.torchscript
zhuhao kwargs encoder= SANMEncoderChunkOpt
zhuhao zhuhao zhuhao model_scripts.shape= 2
rescale encoder modules with factor=18
I20241210 13:38:22.617133 43353 funasr-wss-server-2pass.cpp:407] Failed to download model from modelscope. If you set local asr model path,  you can ignore the errors.
E20241210 13:38:22.617242 43353 funasr-wss-server-2pass.cpp:411] /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model_blade.torchscript do not exists.

我看代码是    

    def export_encoder_forward(
     self,
      speech: torch.Tensor,
     speech_lengths: torch.Tensor,
    ):
    # a. To device
    batch = {"speech": speech, "speech_lengths": speech_lengths, "online": True}
    # batch = to_device(batch, device=self.device)
    enc, enc_len = self.encoder(**batch)
    mask = self.make_pad_mask(enc_len)[:, None, :]
    alphas, _ = self.predictor.forward_cnn(enc, mask)

    return enc, enc_len, alphas

我看export是给的三个参数，这里报了一个expected at most 3 argument(s) but received 4 argument(s). 有点奇怪，请问是什么原因？

**Comment by zhuhao528** [comment]
我把 def forward(self, speech: torch.Tensor, speech_lengths: torch.Tensor, online: bool = False):
改成  def forward(self, speech: torch.Tensor, speech_lengths: torch.Tensor, online):
这个函数的第三个参数取消默认值以后，可以正常导出model_blade.torchscript和decode_blade.torchscript
