### ISSUE TITLE
emotion2vec onnx

### ISSUE THREAD

**Issue by thewh1teagle** [modelscope/FunASR#2291]
Can you add support for onnx with [emotion2vec](https://github.com/modelscope/FunASR/tree/main/funasr/models/emotion2vec)
I tried to add it, I understand that we need to implement `export` method in [model.py](https://github.com/modelscope/FunASR/blob/main/funasr/models/emotion2vec/model.py) and then add `export_meta.py` file and finally export with [export.py](https://github.com/modelscope/FunASR/blob/main/export.py). That's correct?
If so, can you add support for it or guide me how to export it to onnx?
Thanks.

**Comment by LauraGPT** [comment]
Sorry, I am busy now. I evaluate the process of export onnx is easy. You could ref to the docs: https://pytorch.org/docs/stable/onnx_torchscript.html#torch.onnx.export

**Comment by thewh1teagle** [comment]
> Sorry, I am busy now. I evaluate the process of export onnx is easy. You could ref to the docs: https://pytorch.org/docs/stable/onnx_torchscript.html#torch.onnx.export

I tried by the following:

```console
git clone https://github.com/modelscope/FunASR
cd FunASR
uv venv -p 3.9
source .venv/bin/activate
uv pip install -e .

uv pip install torch torchvision torchaudio setuptools pydub onnx onnxconverter_common
uv run export.py
```

with `export.py`:

```py
from funasr import AutoModel
import torch

dummy_input = torch.randn(1, 16000)
model = AutoModel(model="iic/emotion2vec_base_finetuned")
torch.onnx.export(model.model, dummy_input, opset_version=13, input_names=['input'], output_names=['output'])
```

But there's issues with `compute_mask_indices`

https://github.com/modelscope/FunASR/issues/2085

After omitting the invalid arguments it failed with:

<details>

```console
 uv run export.py
/Volumes/Internal/audio/emotion/FunASR/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
funasr version: 1.2.0.
Check update of funasr, and it would cost few times. You may disable it by set `disable_update=True` in AutoModel
You are using the latest version of funasr-1.2.0
Downloading Model to directory: /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned
2024-12-12 13:04:52,124 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.weight, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.0.0.bias, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.1.0.weight, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.1.0.bias, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.2.0.weight, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.2.0.bias, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.3.0.weight, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.blocks.3.0.bias, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.proj.weight, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Warning, miss key in ckpt: modality_encoders.AUDIO.decoder.proj.bias, /Users/user/.cache/modelscope/hub/iic/emotion2vec_base_finetuned/emotion2vec_base.pt
Traceback (most recent call last):
  File "/Volumes/Internal/audio/emotion/FunASR/export.py", line 6, in <module>
    torch.onnx.export(model.model, dummy_input, opset_version=13, input_names=['input'], output_names=['output'])
  File "/Volumes/Internal/audio/emotion/FunASR/.venv/lib/python3.9/site-packages/torch/onnx/__init__.py", line 375, in export
    export(
  File "/Volumes/Internal/audio/emotion/FunASR/.venv/lib/python3.9/site-packages/torch/onnx/utils.py", line 502, in export
    _export(
  File "/Volumes/Internal/audio/emotion/FunASR/.venv/lib/python3.9/site-packages/torch/onnx/utils.py", line 1564, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/Volumes/Internal/audio/emotion/FunASR/.venv/lib/python3.9/site-packages/torch/onnx/utils.py", line 1169, in _model_to_graph
    _set_input_and_output_names(graph, input_names, output_names)
  File "/Volumes/Internal/audio/emotion/FunASR/.venv/lib/python3.9/site-packages/torch/onnx/utils.py", line 1696, in _set_input_and_output_names
    set_names(list(graph.outputs()), output_names, "output")
  File "/Volumes/Internal/audio/emotion/FunASR/.venv/lib/python3.9/site-packages/torch/onnx/utils.py", line 1673, in set_names
    raise RuntimeError(
RuntimeError: number of output names provided (1) exceeded number of outputs (0)
```

</details>

**Comment by thewh1teagle** [comment]
I made some progress here: https://github.com/thewh1teagle/FunASR/commit/586e81deb91daf0da1cbf31eb9b1af902857aaf0. I was able to export the model as ONNX, but currently, it only accepts a fixed input size of a single 16000 sample waveform. Maybe one of you could help with modifying it to accept dynamic input sizes and map the output to label scores?

**Comment by takipipo** [comment]
could you check the work I did on https://github.com/modelscope/FunASR/pull/2359 I did manage to make it accept dynamic input

**Comment by thewh1teagle** [comment]
@takipipo 

Thanks. I can now export it to onnx with

```python
from funasr import AutoModel

model = AutoModel(
    model="iic/emotion2vec_base",
    hub="ms"
)

res = model.export(type="onnx", quantize=False, opset_version=13, device='cpu', output_dir=".")  # mv emotion2vec emotion2vec.onnx
```

I tried to infer it with wav file and I could get matrix output. however I'm not sure what's the specific input and output and how eventually parse the output into dictionary of scores where keys are emotions and values are the score.
