### ISSUE TITLE
vad的pipeline不支持batch推理

### ISSUE THREAD

**Issue by wwfcnu** [modelscope/FunASR#474]
运行环境python3.7、funasr==0.4.5、modelscope=1.5.0、linux
egs_modelscope/vad/TEMPLATE/infer.sh
model="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch"
运行报错如下：
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/audio/voice_activity_detection_pipeline.py", line 63, in __init__
    vad_cmvn_file=self.cmd['vad_cmvn_file'])
  File "/mnt/data1/AudioDataset/FunASR/funasr/bin/vad_inference_launch.py", line 115, in inference_launch
    return inference_modelscope(**kwargs)
  File "/mnt/data1/AudioDataset/FunASR/funasr/bin/vad_inference.py", line 276, in inference_modelscope
    raise NotImplementedError("batch decoding is not implemented")
NotImplementedError: batch decoding is not implemented
```

**Comment by langgz** [comment]
是的，暂时不支持，另外，没有这种使用场景

**Comment by wwfcnu** [comment]
> 忘记修改默认值了，vad确实不支持batch，感谢反馈。 [c197b3a](https://github.com/alibaba-damo-academy/FunASR/commit/c197b3aa85ef7de4fdcfc1f706ab95205fdb8617)

如果我想要实现vad的batch推理，并且希望它兼容m4a格式的语音，我需要修改哪些地方，
对于格式兼容，我能想到的是修改funasr/datasets下面的文件，采用ffmpeg代替torchaudio

**Comment by wwfcnu** [comment]
@langgz 现在最新的版本是不是支持batch推理了
